### ISSUE TITLE
What is the ONEWAYSMS_API

### ISSUE THREAD

**Issue by KoizumiKenta** [vickzkater/onewaysms-laravel#1]
In OnewaySMS API section there's only OnewaySMS username and password there isnt any API 

So what should i put the ONEWAYSMS_API as ?

**Comment by KentKongH** [comment]
Update

I just remove the env('ONEWAYSMS_API') in the line 37 as I found out this will always return '0000 - Auth credentials is not set' 

And now it's working and message can be send

**Comment by KentKongH** [comment]
Update

I just remove the env('ONEWAYSMS_API') in the line 37 as I found out this will always return '0000 - Auth credentials is not set' 

And now it's working and message can be send
